# Generated by Django 5.0.6 on 2026-01-27 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='created_at',
        ),
    ]
